# application.yaml
# Server settings (ServerProperties)
# 以数据为中心的标记语言 ,易于读写 ,替代xml
# springboot 默认是8080端口 ,没有项目地址

# 服务器设置
server:
  port: 8081
  address: 127.0.0.1
  sessionTimeout: 60
  contextPath: /kafkademo

kafka:
  config:
    zk: 192.168.201.50:2181
    groupid: test
    topic: test
    broker: 192.168.201.50:9092
    threadnum: 3

err:
  file:
    path: /






